# Generated by Django 3.2.3 on 2021-06-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0005_remove_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='EN', max_length=2),
        ),
    ]
