# Generated by Django 3.2.3 on 2021-07-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0008_auto_20210701_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='receive_contact',
            new_name='get_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='line',
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.AddField(
            model_name='user',
            name='get_line',
            field=models.BooleanField(default=True),
        ),
    ]
