# Generated by Django 3.2.3 on 2021-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0009_auto_20210701_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
