# Generated by Django 3.2.3 on 2021-07-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0011_auto_20210702_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line_refresh_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
