# Generated by Django 3.2.3 on 2021-07-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0012_user_line_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_line_display_name',
            field=models.BooleanField(default=False),
        ),
    ]
