# Generated by Django 3.2.3 on 2021-07-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0013_user_get_line_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='line',
            field=models.CharField(blank=True, default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='line_access_token',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='line_refresh_token',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='line_state',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
