# Generated by Django 3.2.3 on 2021-07-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0014_auto_20210703_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='get_email',
            new_name='do_get_emails',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='get_line_display_name',
            new_name='do_get_line_display_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='get_line',
            new_name='do_get_lines',
        ),
        migrations.AddField(
            model_name='user',
            name='is_line_friend',
            field=models.BooleanField(default=False),
        ),
    ]
