# Generated by Django 3.2.3 on 2021-07-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0015_auto_20210704_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line',
        ),
    ]
