# Generated by Django 3.2.3 on 2021-07-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0017_rename_line_user_line_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='line_state',
        ),
    ]
