# Generated by Django 3.2.3 on 2021-07-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0018_remove_user_line_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
