# Generated by Django 3.2.3 on 2021-07-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0022_alter_user_do_get_line_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_secret',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
