# Generated by Django 3.2.3 on 2021-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0023_user_random_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_city',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_continent_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_country_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_state_prov',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
