# Generated by Django 3.2.3 on 2021-07-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0024_auto_20210705_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_date',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
