# Generated by Django 3.2.3 on 2021-07-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0027_auto_20210709_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
