# Generated by Django 3.2.3 on 2021-07-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0031_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip_date',
        ),
        migrations.AddField(
            model_name='user',
            name='visit_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='do_get_emails',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='do_get_line_display_name',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='do_get_lines',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_line_friend',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='alerts',
            field=models.ManyToManyField(to='app_name.Alert'),
        ),
    ]
