# Generated by Django 3.2.3 on 2021-07-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0032_auto_20210712_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alerts',
            field=models.ManyToManyField(blank=True, to='app_name.Alert'),
        ),
    ]
