# Generated by Django 3.2.3 on 2021-07-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0035_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ip_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip_continent_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip_country_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip_state_prov',
        ),
    ]
