# Generated by Django 3.2.3 on 2021-07-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0038_rename_alert_name_alert_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='show',
        ),
    ]
