# Generated by Django 3.2.3 on 2021-07-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0039_remove_alert_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
