# Generated by Django 3.2.3 on 2021-07-18 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0042_auto_20210715_1154'),
    ]

    operations = [
    	#migrations.RunSQL("""
		#	INSERT INTO alert
		#""")
	]
