# Generated by Django 3.2.3 on 2021-07-28 12:49

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0043_auto_20210718_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=120)),
                ('venue_name', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=23)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=23)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 21, 49, 24, 914464))),
                ('include_time', models.BooleanField(blank=True, default=False)),
                ('guests', models.ManyToManyField(blank=True, related_name='guests', to=settings.AUTH_USER_MODEL)),
                ('hosts', models.ManyToManyField(blank=True, related_name='hosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
