# Generated by Django 3.2.3 on 2021-07-30 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0046_auto_20210730_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 30, 16, 54, 6, 334843)),
        ),
    ]
