# Generated by Django 3.2.3 on 2021-07-30 07:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0047_alter_event_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guests',
        ),
        migrations.AddField(
            model_name='event',
            name='confirmed_guests',
            field=models.ManyToManyField(blank=True, related_name='confirmed_guests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='interested_guests',
            field=models.ManyToManyField(blank=True, related_name='interested_guests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='unconfirmed_guests',
            field=models.ManyToManyField(blank=True, related_name='unconfirmed_guests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 30, 16, 54, 23, 480431)),
        ),
    ]
