# Generated by Django 4.0 on 2021-12-14 12:57

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0048_auto_20210730_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='unconfirmed_guests',
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='invited_guests',
            field=models.ManyToManyField(blank=True, related_name='invited_guests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 14, 21, 57, 50, 340702)),
        ),
    ]
