# Generated by Django 4.0 on 2021-12-17 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0049_remove_event_unconfirmed_guests_event_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='random_seed1',
            field=models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=23),
        ),
        migrations.AddField(
            model_name='event',
            name='random_seed2',
            field=models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=23),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 17, 11, 57, 10, 242448)),
        ),
    ]
