# Generated by Django 4.0 on 2021-12-17 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0050_event_random_seed1_event_random_seed2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='random_seed1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='random_seed2',
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 17, 13, 15, 4, 228543)),
        ),
    ]
