# Generated by Django 4.0 on 2021-12-17 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0052_event_rand_latitude_event_rand_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 17, 17, 31, 1, 679291)),
        ),
    ]
