# Generated by Django 4.0 on 2021-12-17 11:19

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0053_event_postal_code_alter_event_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='event',
            name='interested_guests',
        ),
        migrations.RemoveField(
            model_name='event',
            name='invited_guests',
        ),
        migrations.AddField(
            model_name='event',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='interested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 17, 20, 19, 20, 916342)),
        ),
    ]
