# Generated by Django 4.0 on 2021-12-19 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0054_remove_event_guests_remove_event_interested_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 19, 23, 22, 44, 712262)),
        ),
    ]
