# Generated by Django 4.0 on 2021-12-26 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0057_image_alter_event_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='app_name.Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 26, 19, 26, 46, 14033)),
        ),
    ]
