# Generated by Django 4.0 on 2021-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0063_remove_image_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='key',
            field=models.CharField(default='nameless.jpg', max_length=40),
        ),
    ]
