# Generated by Django 4.0 on 2021-12-31 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0064_remove_image_url_image_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='include_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=23),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=23),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='postal_code',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='rand_latitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=23),
        ),
        migrations.AlterField(
            model_name='event',
            name='rand_longitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=23),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
