# Generated by Django 4.0 on 2022-01-20 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0067_remove_event_confirmed_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attending_limit',
            field=models.IntegerField(default=999999),
        ),
        migrations.CreateModel(
            name='PlusOnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=40)),
                ('chaperone', models.ManyToManyField(blank=True, related_name='chaperone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
