# Generated by Django 4.0 on 2022-01-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0068_event_attending_limit_plusones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlusOnes',
            new_name='PlusOne',
        ),
    ]
