# Generated by Django 4.0 on 2022-01-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0070_event_plus_ones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='plus_ones',
            field=models.ManyToManyField(blank=True, related_name='plus_ones', to='app_name.PlusOne'),
        ),
    ]
