# Generated by Django 4.0 on 2022-01-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0071_alter_event_plus_ones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='postal_code',
            new_name='area',
        ),
    ]
