"""
Django settings for project_name project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import django_heroku
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

## SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-(j7(p96vyw7r)*)8%u++g8qkkz!v=bwzymi!7a39#py&1dvt(w'

## SECURITY WARNING: don't run with debug turned on in production!

#DEBUG = True
DEBUG = config('DEBUG')
#DEBUG = True if config('NODE_ENV') == 'development' else False
SECRET_KEY = config('SECRET_KEY')
ALLOWED_HOSTS = ['event-horizon-jp.herokuapp.com/', 'localhost']
#ALLOWED_HOSTS=['*']

CORS_ORIGIN_ALLOW_ALL = True

CSRF_COOKIE_NAME = "XSRF-TOKEN"
#CSRF_COOKIE_DOMAIN = 'localhost'
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAMESITE = None
#CORS_ORIGIN_WHITELIST = (
#    'http://:localhost:8080',
#    'http://:localhost:8000',
#		'https://event-horizon-jp.herokuapp.com',
#)
#CORS_ALLOWED_ORIGINS = [
#    'http://localhost:8080',
#    'http://localhost:8000',
#		'https://event-horizon-jp.herokuapp.com',
#]
#CSRF_TRUSTED_ORIGINS = [
#    'localhost:8080',
#    'localhost:8000',
#		'event-horizon-jp.herokuapp.com',
#]
#CORS_ALLOW_METHODS = [
#    'DELETE',
#    'GET',
#    'OPTIONS',
#    'PATCH',
#    'POST',
#    'PUT',
#]

# Application definition
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'app_name',
]

AUTH_USER_MODEL = 'app_name.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
]

ROOT_URLCONF = 'project_name.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_name.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATIC_URL = '/dist/'
STATIC_ROOT = os.path.join(BASE_DIR, 'dist')

# Vue project location
#FRONTEND_DIR = os.path.join(BASE_DIR, 'frontend')
FRONTEND_DIR = BASE_DIR

# Vue assets directory (assetsDir)
STATICFILES_DIRS = [
    os.path.join(FRONTEND_DIR, 'dist/static'),
]

# Webpack output location containing Vue index.html file (outputDir)
TEMPLATES[0]['DIRS'] += [
    os.path.join(FRONTEND_DIR, 'dist'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Activate Django-Heroku.
django_heroku.settings(locals())
